master:
  host: "http://localhost:20801"
  password: "qTdx3NrnYVG5wGoVmNa5Va1LjYcwY7hXQwDcDzP+3Po="
slaves:
  - host: "http://localhost:20802"
    password: "slave1pass"
    sync_items:
      adlists: true
      blacklist: true
      whitelist: false
      regex: true
      groups: true
      dns_records: false
      dhcp: false
      clients: true
      settings: false
  - host: "http://localhost:20803"
    password: "slave2pass"
    sync_items:
      adlists: true
      blacklist: false
      whitelist: true
      regex: true
      groups: true
      dns_records: true
      dhcp: false
      clients: true
      settings: false
sync_trigger:
  schedule: "0 3 * * *"
  api_call: true
  webui: true
  pihole_file_watch: true
logging:
  level: "INFO"
  debug: false
slack:
  webhook_url: "https://hooks.slack.com/services/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"
  #webhook_url: "https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXX"
  notify_on_error: true
sync_retry:
  enabled: true
  count: 3
metrics:
  enabled: true
  collection_interval: "30s"
  enable_top_domains: true
  enable_top_clients: true
  enable_upstreams: true
  enable_cache_metrics: true
  top_items_limit: 10
