version: '3.8'
services:
  pihole-sync:
    build: .
    container_name: pihole-sync
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - /etc/pihole:/var/lib/pihole:ro  # Pi-holeデータディレクトリ（読み取り専用）
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
