master:
    host: http://restored-master.local
    password: restored-password
slaves: []
sync_trigger:
    schedule: ""
    api_call: false
    webui: false
    config_file_watch: false
logging:
    level: ""
    debug: false
slack:
    webhook_url: ""
    notify_on_error: false
sync_retry:
    enabled: false
    count: 0
gravity:
    - restored.com
metrics:
    enabled: false
    collection_interval: 0s
    enable_top_domains: false
    enable_top_clients: false
    enable_upstreams: false
    enable_cache_metrics: false
    top_items_limit: 0
