name: Merge Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v -o pihole-sync ./cmd/main.go
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: pihole-sync-binary
          path: pihole-sync
